name: Build OFRP

on:
  workflow_dispatch

env:
  SYNC_URL: "https://gitlab.com/OrangeFox/sync.git"
  MANIFEST_BRANCH: "9.0"
  DEVICE_TREE_URL: "https://github.com/alanwang233233/twrp_device_tree"
  BUILD_TARGET: "recovery"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:20.04
        options: --privileged
        env:
          DEBIAN_FRONTEND: noninteractive
    permissions:
      contents: write
    strategy:
      matrix:
        DEVICE_NAME: [ Archytas, Archimedes ]
    env:
      DEVICE_TREE_BRANCH: ${{ matrix.DEVICE_NAME }}
      DEVICE_PATH: "device/xiaomi/${{ matrix.DEVICE_NAME }}"
      MAKEFILE_NAME: "omni_${{ matrix.DEVICE_NAME }}"
    steps:
      - name: Display Run Parameters
        run: |
          echo "::group::User Environment Variables"
          echo "Manifest Branch: ${{ env.MANIFEST_BRANCH }}"
          echo "Device Tree URL: ${{ env.DEVICE_TREE_URL }}"
          echo "Device Tree Branch: ${{ env.DEVICE_TREE_BRANCH }}"
          echo "Device Path: ${{ env.DEVICE_PATH }}"
          echo "Device Name: ${{ matrix.DEVICE_NAME }}"
          echo "Makefile Name: ${{ env.MAKEFILE_NAME }}"
          echo "Build Target: ${{ env.BUILD_TARGET }}.img"
          echo "::endgroup::"

      - name: Check Out
        uses: actions/checkout@v3

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Initialize workspace
        run: |
          mkdir workspace
          cd workspace
          echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        id: pwd

      - name: Install sudo compatibility
        run: cp $GITHUB_WORKSPACE/scripts/sudo /usr/local/bin/sudo && chmod +x /usr/local/bin/sudo

      - name: Prepare the build environment
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y bash git aria2 curl axel wget unzip make libncurses5 m4 rsync openjdk-17
          git clone https://gitlab.com/OrangeFox/misc/scripts
          cd scripts
          bash setup/android_build_env.sh
          sed -i 's/cd -/cd ../g' setup/install_android_sdk.sh
          bash setup/install_android_sdk.sh
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

      - name: Sync OrangeFox sources and minimal manifest
        run: |
          cd ${{ steps.pwd.outputs.workspace-folder }}
          git clone ${{ env.SYNC_URL }}
          cd sync/legacy
          ./orangefox_sync_legacy.sh --branch ${{ env.MANIFEST_BRANCH }} --path ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ env.MANIFEST_BRANCH }}
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

      - name: Clone device tree
        run: |
          cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ env.MANIFEST_BRANCH }}
          git clone ${{ env.DEVICE_TREE_URL }} -b ${{ env.DEVICE_TREE_BRANCH }} ./${{ env.DEVICE_PATH }}
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Switch to Python2
        run: apt-get install -y python2 python-is-python2
        continue-on-error: true

      - name: Building recovery
        run: |
          cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ env.MANIFEST_BRANCH }}
          set +e
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          set -e
          lunch ${{ env.MAKEFILE_NAME }}-eng && make clean && mka adbd ${{ env.BUILD_TARGET }}image -j$(nproc --all)
        shell: bash
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}
        continue-on-error: true

      - name: Check the output directory before uploading
        run: |
          ls -al ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ env.MANIFEST_BRANCH }}/out/target/product/
          echo
          ls -al ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ env.MANIFEST_BRANCH }}/out/target/product/${{ matrix.DEVICE_NAME }}/

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ env.MANIFEST_BRANCH }}/out/target/product/${{ matrix.DEVICE_NAME }}/*.img
            ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ env.MANIFEST_BRANCH }}/out/target/product/${{ matrix.DEVICE_NAME }}/*.zip
          name: OFRP-${{ matrix.DEVICE_NAME }}-${{ github.run_id }}
          tag_name: ofrp-${{ matrix.DEVICE_NAME }}-${{ github.run_id }}
          body: |
            Recovery name: OrangeFox Recovery Project
            Manifest: ${{ env.MANIFEST_BRANCH }}
            Device: ${{ matrix.DEVICE_NAME }}
            Target: ${{ env.BUILD_TARGET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
